### ISSUE TITLE
Ability to Use Simple Price and Not Configurable

### ISSUE THREAD

**Issue by derekclayton** [sprankhub/Spranks_ConfigurableTierPrices#28]
I have a client that has a configurable product, but the pricing is different for each simple. They would like to combine the total items purchased as you are doing, but apply the pricing from the simple products and not the configurable. Any ideas?

**Comment by sprankhub** [comment]
This is not supported and will probably never be supported. There are extensions, which take the prices from the simple products like [BCP](https://bitbucket.org/netresearch/dmp_betterconfigurableproducts), but I do not know what happens if you use both extensions. To be honest, by using both extensions, it is totally unclear what should happen - example:

- Same configurable product - base price 10 EUR.
- Variant A tier price >= 2 pcs 9 EUR.
- Variant B tier price >= 2 pcs 8 EUR.
- Put 1 variant A in cart.
- Put 1 variant B in cart.
- What price do you expect? If you ask me, the price is undefined in this case. It is totally unclear if it is 8 + 8 ; 9 + 9 or even 8 + 9 EUR.

**Comment by derekclayton** [comment]
I was unable to find a combination of extensions that worked together.

Personally we want it to disregard the pricing within the configurable and use the simple prices - but apply the combined quantity of the configurable.

Variant A price: qty 1 = 10.00, qty 10 = 5.00
Variant B price: qty 1 = 20.00, qty 10 = 10.00
If 5 of each are purchased it would be A = 5 * 5.00 plus B = 5 * 10.00 for a total of 75.00
